### ISSUE TITLE
Errant Title 50 Amendment date

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#120]
Title 50 received_on 2019-02-08 had volume 12 amendment date switched to June 12, 2018 after previous being `Dec. 20, 2018`. I'm not sure what date this should be, probably should talk to OFR. We already have patches in for when that same volume changes to Jan. 4, 20199 on the next changed title_version 4 days later. 

<img width="464" alt="Screen Shot 2019-07-26 at 3 32 46 PM" src="https://user-images.githubusercontent.com/3782822/61984836-ea3aa300-afba-11e9-839b-c0e3d64658b1.png">

**Comment by peregrinator** [comment]
So the issue here looks to be caused by OFR catching up from the government shutdown. The amendment date entered incorrectly 'June 12, 2018' is when the FR document published (the effects of that document expire on Jan 3, 2019 - related to fishing quotas). The editor should have put in Jan 4, 2019 as the amendment date here I believe.

So to fix we'll need to do a couple things
- [x] patch the amendment date to be `Jan 4, 2019`
- [ ] after reimport mark the sections in Vol 12 in the `2019-02-12T05...` update as substantive (the amendment date won't change so we'll need to manually fix that in admin)

**Comment by barefootford** [comment]
It looks like this was fixed by Bob In October:
https://github.com/criticaljuncture/ecfr-xml-corrections/commit/f0988000bdc128598312af32f4fc3e7e9fcab633
