### ISSUE TITLE
Title 12 structure and amendment date issues

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#122]
Title 12 appears to have both some structural issues and amendment date issues that may require some OFR input/fixes.

## Volume 5 Amendment date
Volume 5 is amended on 2019-03-08 from `Feb. 20, 2019` to `Jan. 1, 2019`. This might have been an accidental amendment date switch? It was only only present for 6 days before becoming `March 6, 2019.`

Volume 6 was also amended to `Jan. 1, 2019` so it may be that it should remain Feb. 20, 2019.
<img width="735" alt="Screen Shot 2019-07-26 at 4 18 28 PM" src="https://user-images.githubusercontent.com/3782822/61986173-389f7000-afc2-11e9-8438-336a85e70c7d.png">

## Mangled Chapter tags
There are numerous head tags and closing tags in incorrect places. We have patches for these but these appear to still be broken in the latest source xml. Additionally, it doesn't look like we're processing these TOCs correctly so there may be more to add. 

We can try parsing this with nokogiri and seeing seeing where nodes are still missing. 

### Chapter XVII
- Subchapter A head tag outside of DIV4
- Subchapter B head tag outside of DIV4 

### Chapter XVIII
We're not linking to this at all
<img width="956" alt="Screen Shot 2019-07-26 at 5 03 34 PM" src="https://user-images.githubusercontent.com/3782822/61986932-5e7b4380-afc7-11e9-8922-7bed0f191437.png">

<img width="544" alt="Screen Shot 2019-07-26 at 4 05 09 PM" src="https://user-images.githubusercontent.com/3782822/61986952-89fe2e00-afc7-11e9-9f5a-6ef0cb4b18b5.png">

This appears to be present in the structure JSON, not sure what's processing incorrectly but probably an XML issue.

**Comment by peregrinator** [comment]
Put in a basecamp about the amendment date change: https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/109227233/comments

The ToC portion for Chapter XVII looks to have been a patch issue. We left in an extra `<HEAD />` tag that was present in the broken source when we generated the patch. I updated the patch in ff8c71.

I also put in a note in basecamp to get them to make the fixes: https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/109226138/comments

**Comment by peregrinator** [comment]
According to Steve's response the problem is a bit different than what we thought.

Up until the 2019-03-08 update Volume 6 was an empty placeholder, the previous content having been removed on Oct 11, 2018. In the 2019-03-08 update Steve split Volume 5 up and placed part of it in Volume 6 (Volume 5 was essentially too big).

The editor used Jan 1, 2019 as the date because this is when the quarterly revision happened.

For amendment date purposes both Vol  5 and Vol 6 should have had their amendment date set as `Feb 20, 2019`. This date should persist until it is changed again (a few updates for Vol 5 it looks like, a bit longer for Vol 6).
 - [ ] add patch for this!

**Comment by barefootford** [comment]
It looks like @peregrinator has made a fix for this and merged into master. Going to close this issue out.

https://github.com/criticaljuncture/ecfr-xml-corrections/commit/e8c7fed5bc2617b6d2915413e6b448e899c90f6f
