### ISSUE TITLE
Ask OFR about empty parts wrapping Title 24 Appendix

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#19]
Title 24 contains a reserved appendix that is wrapped in a blank part. 

Right now we validate that content versions belong to a parent part. 

Title 24
2017-04-20
source xml:

```
<DIV2 N="Subtitle A" TYPE="SUBTITLE">
  <HEAD>Subtitle A - Office of the Secretary, Department of Housing and Urban Development</HEAD>
	...
  <DIV5 N="94-99" TYPE="PART">
    <HEAD>PARTS 94-99 [RESERVED]</HEAD>
  </DIV5>

  <DIV5 N="" TYPE="PART">
    <HEAD></HEAD>
    <DIV9 N="" TYPE="APPENDIX">
      <HEAD>Appendixes A-C to Subtitle A [Reserved]</HEAD>
    </DIV9>
  </DIV5>
</DIV2>
```

**Comment by peregrinator** [comment]
GPO inserts a PART into the XML to wrap an APPENDIX to SUBPART A in Title 24. This is a correct for this title but GPO requires sections/appendices to be in a part. We will need to deal with appendix if it ever gets content - but since we don't link to or render reserved nodes we can ignore it for now. 

Related Badger: https://app.honeybadger.io/projects/51157/faults/38461198#notice-summary
